# Generated by Django 4.1.3 on 2022-11-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_link',
            new_name='application_url',
        ),
    ]
