# Generated by Django 4.1.3 on 2022-11-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_contact_company_application_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_title',
            field=models.SlugField(default='code janitor'),
            preserve_default=False,
        ),
    ]
