# Generated by Django 4.1.3 on 2022-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_application_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='job_title',
            field=models.CharField(max_length=50),
        ),
    ]
